- name: Deploy config using variable and template
  hosts: all 
  become: yes 

  var_files: 
    - vars.yaml

  tasks: 
    - name: Print the variables first
      debug: 
        msg: "Application {{}} is running on the port {{}} for the {{}} environment."
        
    - name: Create app directory
      file:
        path: /etc/myapp
        state: directory
        owner: root
        group: root
        mode: '0755'
        
    - name: Deploy App Configuration 
      template: 
        src: templates/app.conf.j2
        dest: /etc//myapp/app.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart myapp

  handlers: 
    - name: Restart myapp 
      service: 
        name: myapp 
        state: restarted 
