# ---------- BUILD STAGE -----------

FROM node:18 AS builder

# Set Working Directory 
WORKDIR /app 

# Copy Package.json and install dependencies 
COPY package*.json ./
RUN npm install 

# Copy rest of the code 
COPY . .

# Build the app 
RUN npm run build 


# ---------- RUNTIME STAGE ---------
FROM node:18-slim

WORKDIR /app 

# copy only build output + node_module from builder 
COPY --from=builder /app/node_module from builder 
COPY --from=builder /app/dist ./dist

#Expose port 
EXPOSE 3000

# start the app
CMD ["node", "dist/server.js"]
