# Base Image 
FROM node:18-alpine

# Set Environment Variable 
ENV APP_PORT=3000 \
    APP_MESSAGE="Hello From Docker Script 03."

# Set Working Directory
WORKDIR /app

# Copy Files 
COPY server.js . 

# Expose the port
EXPOSE 3000

# Run the application
CMD ["node", "server.js"]
