---
- name: Basic playbook - install and start NGINX
  hosts: all
  become: yes 

  tasks: 
    - name: Install nginx package 
      ansible.builtin.package: 
        name: nginx 
        state: present
        
    - name: Start and enable nginx service 
      ansible.builtin.service: 
        name: nginx 
        state: started 
        enabled: yes
